backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/images
public_folder: images
# Uncomment local_backend when you need to develop in your local
local_backend: true # run npx netlify-cms-proxy-server for local testing
collections:
  - name: "pages"
    label: "Sivut"
    files:
    - label: "Etusivu"
      name: "home"
      file: "content/home.json"
      fields:
        - label: "Herokuva"
          name: "Hero"
          widget: object
          fields:
            - { label: "Otsikko", name: "HeroTitle", widget: "string"}
            - { label: "Alaotsikko", name: "HeroSubtitle", widget: "string"}
            - { label: "Pöytäkoneen Herokuva", name: "DesktopHeroImage", widget: "string"}
            - { label: "Mobiilin Herokuva", name: "MobileHeroImage", widget: "string"}
            - { label: "Toimintakehotteen teksti", name: "CTA", widget: "string"}
            - { label: "Linkki", name: "CtaLink", widget: "string"}
            - { label: "Näytetäänkö Vaalinumero?", name: "DisplayElectionNumber", widget: "boolean"}
            - { label: "Vaalinumero", name: "ElectionNumber", widget: "string"}
        - label: 'Teemat-osio'
          name: "ThemeSection"
          widget: object
          fields:
          - { label: "Osion otsikko", name: "SectionTitle", widget: "string" }  
          - label: "Teemat"
            name: "themes"
            widget: list
            fields:
              - { label: "Teeman otsikko", name: "title", widget: "string"}
              - { label: "Kuvaus", name: "description", widget: "text"}
              - { label: "Kuva", name: "image", widget: "image" }
              - { label: "Napin teksti", name: "cta", widget: "string"}
              - { label: "Linkki", name: "link", widget: "string"}
        - label: "Referenssit-osio"
          name: "ReferenceSection"
          widget: object
          fields:
          - { label: "Osion otsikko", name: "SectionTitle", widget: "string" }  
          - label: "Referenssit"
            name: "referees"
            widget: list
            fields:
              - { label: "Referoija", name: "referee", widget: "string"}
              - { label: "Referoijan nimike", name: "refereeTitle", widget: "string"}
              - { label: "Referenssi", name: "reference", widget: "text"}
              - { label: "Kuva", name: "image", widget: "image" }
        - label: "Sivuston metatiedot"
          name: "meta"
          widget: object
          fields:
          - { label: "Sivun otsikko", name: "title", widget: "string"}
          - { label: "Sivun kuvaus", name: "description", widget: "Vahvan talouden Turku"}
          - { label: "Sivun linkki", name: "url", widget: "string"}
          - { label: "Sivun kuva", name: "image", widget: "image"}
          - { label: "Twitter-tili", name: "twitter", widget: "@juho_koli"}
  - name: "general"
    label: "Sivun asetukset"
    files:
    - label: "Yleiset osiot"
      name: "site"
      file: "content/site.json"
      fields:
        - label: "Yläpalkki"
          name: "Header"
          widget: object
          fields:
           - { label: "Logo", name: "logo", widget: "string"}
           - { label: "Mobiili Kokoomuslogo", name: "mobileImageLogo", widget: "image"}
           - { label: "Mobiiliu Kokoomuslogon täsmennys", name: "mobileImageAlt", widget: "string"}
           - { label: "Etusivu", name: "homeTitle", widget: "string"}
           - { label: "Vaaliteemat", name: "themesTitle", widget: "string"}
           - { label: "Juho", name: "aboutMeTitle", widget: "string"}
           - { label: "Ota Yhteyttä", name: "contactTitle", widget: "string"}
        - label: "Uutiskirje"
          name: "newsletter"
          widget: object
          fields:
          - { label: "Logo", name: "logo", widget: "image"}
          - { label: "Otsikko", name: "title", widget: "string"}
          - { label: "kuvaus", name: "description", widget: "string"}
          - { label: "Toimintakehotteen teksti", name: "cta", widget: "string"}
          - { label: "Taustakuva", name: "backgroundImage", widget: "image"}
          